services:
  api-passos-magicos:
    build: .
    container_name: api-passos-magicos
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./docs:/app/docs
      - ./models:/app/models
      - ./mlruns:/app/mlruns
    environment:
      - PYTHONUNBUFFERED=1
      - DB_PATH=/app/data/monitoring.db 
    restart: always